---
platform: linux
image: docker:///java#8
inputs:
  - name: pcfdemo
  - name: candidate-release
  - name: version
run:
  path: pcfdemo/ci/tasks/rename-artifact.sh
  args: ["-d", "candidate-release", "-v", "version/number"]
