---
platform: linux

image: docker:///java#8

inputs:
  - name: pcfdemo
  - name: build
  - name: version

run:
  path: pcfdemo/ci/tasks/rename-artifact.sh
  args: [ "-d", "build", "-v", "version/number" ]
